/* global
	global, document, demand, provide, queue, processor, settings
*/

var DEMAND_ID               = 'demand',
	PROVIDE_ID              = 'provide',
	PATH_ID                 = 'path',
	MODULE_PREFIX           = '/' + DEMAND_ID + '/',
	MODULE_PREFIX_HANDLER   = MODULE_PREFIX + 'handler/',
	MODULE_PREFIX_FUNCTION  = MODULE_PREFIX + 'function/',
	MODULE_PREFIX_VALIDATOR = MODULE_PREFIX + 'validator/',
	NULL                    = null,
	UNDEFINED               = undefined,
	FALSE                   = false,
	TRUE                    = true,
	STRING_UNDEFINED        = 'undefined',
	STRING_STRING           = 'string',
	STRING_BOOLEAN          = 'boolean',
	STRING_OBJECT           = 'object',
	STRING_FUNCTION         = 'function',
	STRING_NUMBER           = 'number',
	FUNCTION_EMPTY          = function() {},
	EVENT_PREFIX            = 'pre',
	EVENT_POSTFIX           = 'post',
	EVENT_CONFIGURE         = 'Configure',
	EVENT_PRE_CONFIGURE     = EVENT_PREFIX + EVENT_CONFIGURE,
	EVENT_POST_CONFIGURE    = EVENT_POSTFIX + EVENT_CONFIGURE,
	EVENT_CACHE             = 'cache',
	EVENT_CACHE_MISS        = EVENT_CACHE + 'Miss',
	EVENT_CACHE_HIT         = EVENT_CACHE + 'Hit',
	EVENT_CACHE_CLEAR       = EVENT_CACHE + 'Clear',
	EVENT_CACHE_EXCEED      = EVENT_CACHE + 'Exceed',
	EVENT_REQUEST           = 'Request',
	EVENT_PRE_REQUEST       = EVENT_PREFIX + EVENT_REQUEST,
	EVENT_POST_REQUEST      = EVENT_POSTFIX + EVENT_REQUEST,
	EVENT_PROCESS           = 'Process',
	EVENT_PRE_PROCESS       = EVENT_PREFIX + EVENT_PROCESS,
	EVENT_POST_PROCESS      = EVENT_POSTFIX + EVENT_PROCESS,
	EVENT_QUEUE             = 'queue',
	EVENT_QUEUE_ENQUEUE     = EVENT_QUEUE + 'Enqueue',
	EVENT_QUEUE_DEQUEUE     = EVENT_QUEUE + 'Dequeue';