var arrayPrototype                 = Array.prototype,
	arrayPrototypeSlice            = arrayPrototype.slice,
	arrayPrototypeConcat           = arrayPrototype.concat,
	objectPrototype                = Object.prototype,
	objectCreate                   = Object.create,
	objectDefineProperty           = Object.defineProperty,
	objectGetOwnPropertyNames      = Object.getOwnPropertyNames,
	objectGetOwnPropertyDescriptor = Object.getOwnPropertyDescriptor,
	functionPrototype              = Function.prototype;